config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/error',to:'static_pages#error',as: :error
  get '/not_found',to:'static_pages#not_found',as: :not_found

  devise_for :users,controllers: { sessions: 'users/sessions' ,passwords: 'users/passwords',
                                    registrations:'users/registrations',confirmations:'users/confirmations'}

    get 'profile/student_dashboard' => 'profiles#student_dashboard', as: :student_dashboard
    get 'profile/employer_dashboard' => 'profiles#employer_dashboard', as: :employer_dashboard

    get 'profile/:id' => 'profiles#show' , as: :profile

  resources :tests do
    member do
     get :activate
     get :privacy
     get :result
    end
    resources :questions ,:only => [:new, :create]
  end

  resources :questions ,:only =>[:show]

  get 'taketest/:test_id' , to: 'enrollments#taketest' , as: :taketest

  get 'taketest/:test_id/finish',to: 'enrollments#finish',as: :finish
  get 'taketest/:test_id/timeup',to: 'enrollments#timeup'
  post 'taketest/:test_id/submit_clicked' ,to: 'enrollments#submit_clicked', as: :submit_clicked

  get 'show_current_question/:id', to: 'enrollments#show_current_question' ,as: :show_current_question

  post 'add_question_to_current_test/:test_id/:question_id' , to: 'tests#add_question_to_current_test' ,as: :add_question_to_current_test
  delete 'remove_question_from_current_test/:test_id/:question_id' , to: 'tests#remove_question_from_current_test' ,as: :remove_question_from_current_test

  get 'enroll_for_test/:test_id' , to: 'enrollments#enroll_for_test',as: :enroll_for_test

  get 'details/edit',to:'details#edit',as: :edit_details
  get '/details/edit_student_details',to:'details#edit_student_details',as: :edit_student_details
  get '/details/new_student_details',to:'details#new_student_details',as: :new_student_details
  post '/student_details',to:'details#create_student_details'
  put '/student_details',to:'details#update_student_details'
  patch '/student_details',to:'details#update_student_details'

  get '/details/edit_employer_details',to:'details#edit_employer_details',as: :edit_employer_details
  get '/details/new_employer_details',to:'details#new_employer_details',as: :new_employer_details
  post '/employer_details',to:'details#create_employer_details'
  put '/employer_details',to:'details#update_employer_details'
  patch '/employer_details',to:'details#update_employer_details'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :a,:b,:c,:d

  #This works
  [:correct_answer,:options].each do |t|
    serialize t,Array
  end

  #with test
  has_many :test_questions,dependent: :destroy
  has_many :tests ,through: :test_questions

  #with category
  belongs_to :category

  belongs_to :employer
  #validations
  validates :question,
             presence:true

  validates :question_type,
             presence:true,
             numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2 }

  #options
  validate :option_map_for_different_question_type

  #correct_answers
  validate :correct_answers_map_for_different_question_type

  def option_map_for_different_question_type
    case self.question_type
      when 0
        if self.options.any?{|x| !x.empty? }
          errors.add( :options,"Options not allowed for integer type" )
        end
      when 1
        if self.options.all?{|x| x.empty? }
          errors.add(:options,"Needs all options")
        end
      when 2
        if self.options.all?{|x| x.empty? }
          errors.add( :options,"Needs all option" )
        end
      end
  end

  def correct_answers_map_for_different_question_type
    case self.question_type
      when 0
        if correct_answer[0].empty?
          errors.add(:correct_answer,"Need answer for integer type")
        end
      when 1
        if no_of_answer != 1
          errors.add(:correct_answer,"Incorrect  number of answer")
        end
      when 2
        if no_of_answer < 2
          errors.add(:correct_answer,"Incorrect  number of answer")
        end
    end
  end

  def no_of_answer
    number = 0
    correct_answer.each do |x|
      number += 1 if !x.empty?
    end
    number
  end

  #instance methods


  #class methods
  def self.get_questions_excluding(test_question_ids)
    Question.where.not(id:test_question_ids)
  end

  def self.get_question_by_id(id)
    Question.find(id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :check_user

  def new
    @test=Test.find(params[:test_id])
    @question=Question.new

  end

  def index
    @questions=Question.all
  end

  def create
    #should logged and should be employer
    @question=current_user.questions.build(question_params)
    @test=Test.find(params[:test_id])
    if @question.save
      flash[:success]="Question added to Bank successfully"
      redirect_to test_path(@test)
    else
      @question.a=@question.options[0]
      @question.b=@question.options[1]
      @question.c=@question.options[2]
      @question.d=@question.options[3]
      render 'new'
    end
  end

  def destroy
    @question=Question.find(params[:id])
    if @question.destroy
      flash[:success]="Question Removed from Question bank"
      redirect_to test_path(id:params[:test_id])
    end
  end

  def show
    @question=Question.find(params[:id])
  end

  private
  def question_params
    #passing options and correct answers as arrays
    p params.require(:question).permit(:category_id,:question_type,:question,options:[],correct_answer:[])
  end

  def check_user
    unless current_user.type=="Employer"
      flash[:danger]="Authorizaion Error"
      redirect_to error_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  # def getMarks
  #   return 5;
  # end
end

app/views/questions/_question.html.erb
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Marks</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td>
            <strong><%=question.question%></strong>
          </td>
          <%if current_user.id==@test.employer_id%>
          <td>
            <%= form_tag(add_question_to_current_test_path(test_id:@test.id,question_id:question.id),remote:true,class:"form-inline") do %>
              <div class="form-group">
                <%=number_field_tag "marks",'1',min:'1'%>
              </div>
              <div class="form-group">
                 <%= submit_tag("Add",class:'btn btn-success')%>
              </div>
            <%end%>
          </td>
          <td><%=link_to "view",question_path(question)%></td>
          <% end %>
        </tr>
        <!--Converted from link_to  form to passs marks to add_  -->
      <%- end %>
      </tbody>
    </table>
</div>

app/views/questions/index.html.erb
<div class = "qcategory" >
  <%= label_tag :filter, "Select Category" %>
  <%= collection_select :filter, :category_id, Category.all, :id, :name%>
</div>
<ul class = "questions" >
  <%= render @questions %>
</ul>
<%= link_to "Create New", new_question_path%>

app/views/questions/new.html.erb
<div class = "panel panel-info" >
  <div class = "panel-heading" >
    <h3 class = "panel-title" > Create Question </h3>
  </div>
  <div class = "panel-body" >
    <div class = "form-horizontal" >
      <%= form_for( [@test,@question] ) do |f| %>
        <%= render 'shared/error_messages',object: f.object %>
            <div class = "qtype form-group" >
              <%= f.label :question_type %><br/>
              <%= f.label :question_type, "Single Answer Correct" %>
              <%= f.radio_button :question_type, 1 , :checked => true %>
              <%= f.label :question_type, "Multiple Correct Answer" %>
              <%= f.radio_button :question_type, 2 %>
              <%= f.label :question_type, "Integer Answer" %>
              <%= f.radio_button :question_type, 0 %>
            </div>
            <div class = "qcategory  form-group" >
              <%= f.label :category, "Select Category" %>
              <%= f.collection_select :category_id, Category.all, :id, :name, :class => "select form-control" %>
            </div>
            <div id = "question" class = "form-group" >
              <%= f.label :question %><br/>
              <%= f.text_area :question, autofocus: true %>
            </div>
            <div id = "options" class = "form-group" >
              <div>
                <div class = "option_1" >
                  <%= f.label :a %><br/>
                  <%= f.text_field :a, autofocus: true, name: 'question[options][]' %>
                </div>
                <div class = "option_2" >
                  <%= f.label :b %><br/>
                  <%= f.text_field :b, autofocus: true, name: 'question[options][]' %>
                </div>
                <div class = "option_3" >
                  <%= f.label :c %><br/>
                  <%= f.text_field :c, autofocus: true, name: 'question[options][]' %>
                </div>
                <div class = "option_4" >
                  <%= f.label :d %><br/>
                  <%= f.text_field  :d, autofocus: true, name: 'question[options][]' %>
                </div>
              </div>
            </div>
            <div id = "correct_answer" >
              <div id = "correct_answers_1" >
                <%= f.label :correct_answer %><br/>
                <%= f.label :correct_answer, "A" %>
                <%= f.radio_button :correct_answer, 'A' , :checked => true, name:'question[correct_answer][]' %>
                <%= f.label :correct_answer, "B" %>
                <%= f.radio_button :correct_answer, 'B', name:'question[correct_answer][]' %>
                <%= f.label :correct_answer, "C" %>
                <%= f.radio_button :correct_answer, 'C', name:'question[correct_answer][]' %>
                <%= f.label :correct_answer, "D" %>
                <%= f.radio_button :correct_answer, 'D' , name:'question[correct_answer][]' %>
              </div>
              <div id = "correct_answers_2" >
                <%= f.label :correct_answer %><br/>
                <%= f.label :correct_answer, "A" %>
                <%= f.check_box :correct_answer, { multiple:true , checked:true }, 'A' , nil %>
                <%= f.label :correct_answer, "B" %>
                <%= f.check_box :correct_answer, { multiple:true },'B', nil %>
                <%= f.label :correct_answer, "C" %>
                <%= f.check_box :correct_answer,{ multiple:true },'C',  nil %>
                <%= f.label :correct_answer, "D" %>
                <%= f.check_box :correct_answer,{ multiple:true },'D',  nil %>
              </div>
              <div id = "correct_answers_0" >
                <%= f.label :correct_answer %>
                <%= f.text_field :correct_answer, name:'question[correct_answer][]' %>
              </div>
            </div>
            <%= f.submit "Add Question", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/show.html.erb
<div>
  <div>
      <%if @question.question_type==0%>
        <h3>Integer Answer Correct</h3>
      <%elsif @question.question_type==1%>
        <h3>Single Answer Conrrect</h3>
      <%else%>
        <h3>Single Answer Conrrect</h3>
      <%end%>
  </div>
  <div>
    <br>
      <h1><%=@question.question%></h1>
  </div>
  <div>
    <br>
    <%unless @question.question_type==0%>
    <h3>Options:</h3>
    <h3>A=> <%=@question.options[0]%></h3>
    <h3>B=> <%=@question.options[1]%></h3>
    <h3>C=> <%=@question.options[2]%></h3>
    <h3>D=> <%=@question.options[3]%></h3>
    <%end%>
  </div>
  <div>
    <br>
    <h3>Correct Answer:</h3>
    <h3><%=@question.correct_answer%></h3>
  </div>
</div>