config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/error',to:'static_pages#error',as: :error
  get '/not_found',to:'static_pages#not_found',as: :not_found

  devise_for :users,controllers: { sessions: 'users/sessions' ,passwords: 'users/passwords',
                                    registrations:'users/registrations',confirmations:'users/confirmations'}

    get 'profile/student_dashboard' => 'profiles#student_dashboard', as: :student_dashboard
    get 'profile/employer_dashboard' => 'profiles#employer_dashboard', as: :employer_dashboard

    get 'profile/:id' => 'profiles#show' , as: :profile

  resources :tests do
    member do
     get :activate
     get :privacy
     get :result
    end
    resources :questions ,:only => [:new, :create]
  end

  resources :questions ,:only =>[:show]

  get 'taketest/:test_id' , to: 'enrollments#taketest' , as: :taketest

  get 'taketest/:test_id/finish',to: 'enrollments#finish',as: :finish
  get 'taketest/:test_id/timeup',to: 'enrollments#timeup'
  post 'taketest/:test_id/submit_clicked' ,to: 'enrollments#submit_clicked', as: :submit_clicked

  get 'show_current_question/:id', to: 'enrollments#show_current_question' ,as: :show_current_question

  post 'add_question_to_current_test/:test_id/:question_id' , to: 'tests#add_question_to_current_test' ,as: :add_question_to_current_test
  delete 'remove_question_from_current_test/:test_id/:question_id' , to: 'tests#remove_question_from_current_test' ,as: :remove_question_from_current_test

  get 'enroll_for_test/:test_id' , to: 'enrollments#enroll_for_test',as: :enroll_for_test

  get 'details/edit',to:'details#edit',as: :edit_details
  get '/details/edit_student_details',to:'details#edit_student_details',as: :edit_student_details
  get '/details/new_student_details',to:'details#new_student_details',as: :new_student_details
  post '/student_details',to:'details#create_student_details'
  put '/student_details',to:'details#update_student_details'
  patch '/student_details',to:'details#update_student_details'

  get '/details/edit_employer_details',to:'details#edit_employer_details',as: :edit_employer_details
  get '/details/new_employer_details',to:'details#new_employer_details',as: :new_employer_details
  post '/employer_details',to:'details#create_employer_details'
  put '/employer_details',to:'details#update_employer_details'
  patch '/employer_details',to:'details#update_employer_details'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :authenticate_user!
def show
    @user = current_user
    if @user.type == "Student"
      redirect_to student_dashboard_path
    else
      redirect_to employer_dashboard_path
    end
  end
#Method for loading employer dashboard
#Employer must be logged in
  def employer_dashboard
    #send query parameter for filteration
    @tests = Test.employer_test_which_are(current_user,params[:q])
  end
#Method for loading Student dashboard
#enrolled test shows all enrolled test by the current student user
#tests are fetched from database which include all active test.
  def student_dashboard
    #send query paramater and enrolled test for filteration
    @enrolled_test = Enrollment.all.where(student_id:current_user.id).pluck(:test_id)
    @tests = Test.student_test_which_are_enrolled(current_user,params[:q],@enrolled_test,params[:page])
 end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def test_attempted(test_id)
    en=Enrollment.find_by(test_id:test_id,student_id:current_user.id)
    en.attempted
  end
end

app/views/profiles/employer_dashboard.html.erb
<span>
    <h1>
        Dash Board
    </h1>
</span>
<h2 class="pull-left center"><%= link_to "Create Test",new_test_path ,:class => "btn btn-success" %></h2>
<!-- partial for lising tests ,works even if @tests is not passed,because @tests is defined in action -->
<%=render 'tests/test',collection:@tests%>
<!-- renders tests/_test.html.erb -->

app/views/profiles/show.html.erb
<span class="LogoutButton white-text">
  <%= link_to "Logout", destroy_user_session_path %>
</span>
<h1 class=" white-text">
  <%= @user.name %>'s Dashboard
</h1>
<p>
  <%= @user.name %>
</p>

app/views/profiles/student_dashboard.html.erb
<div>
    <h1 class="">
        <%= current_user.name %>'s Dashboard
    </h1>
    <table class="table">
        <tr>
            <th class="">Name</th>
            <th>Duration</th>
            <th>Date</th>
            <th>Number Of Questions</th>
            <th>Marks</th>
            <th>Status</th>
            <th></th>
            <th></th>
        </tr>

        <div id="test_listing_for_student">
            <% @tests.each do |test| %>
            <tr>
                <td><%= test.name %></td>
                <td><%= test.duration.strftime('%H:%M')%></td>
                <td><%= test.date%></td>
                <td><%= test.number_of_questions%></td>
                <td><%= test.marks%></td>

                <%if DateTime.now.utc.to_date < test.date%>
                <% if @enrolled_test.include? test.id%>
                  <td style="margin:10px;" class="btn btn-success">
                      <%= link_to "Enrolled",'#',:class => "no-link" %>
                  </td>
                <%else%>
                  <td style="margin:10px;">
                      <%= link_to "Enroll",enroll_for_test_path(test, page: params[:page]),remote:true,:class => "btn btn-primary no-link" %>
                  </td>
                <% end %>

                <%elsif DateTime.now.utc.to_date ==test.date%>
                  <%if @enrolled_test.include? test.id%>
                    <%if test_attempted(test.id)%>
                      <td style="margin:10px;" class="btn btn-success">
                          <%= link_to "Result",result_test_path(test),:class => "no-link" %>
                      </td>
                    <%else%>
                      <td style="margin:10px;" class="btn btn-success">
                          <%= link_to "Take Test",taketest_path(test),:class => "no-link" %>
                      </td>
                    <%end%>
                  <%else%>
                    <td style="margin:10px;">
                        <%= link_to "Enroll",enroll_for_test_path(test, page: params[:page]),remote:true,:class => "btn btn-primary no-link" %>
                    </td>
                  <%end%>
                <%else%>
                  <td style="margin:10px;" class="btn btn-success">
                      <%= link_to "Result",result_test_path(test),:class => "no-link" %>
                  </td>
                <%end%>
            </tr>
            <% end %>
        </div>
    </table>
    <%= paginate @tests , :params => {:controller => 'profiles',:action => 'student_dashboard'} %>
</div>

app/views/profiles/student_details.html.erb
<%= form_for @student_details,url: profiles_student_details_path,method:'POST' do |f| %>
    <div class="col-lg-4">
        <%= f.label :age %>
        <%= f.number_field :age %>
    </div>

    <div class="col-lg-4">
        <%= f.label :college %>
        <%= f.text_field :college %>
    </div>

    <div class="col-lg-4">
        <%= f.label :experience,"Experience in years" %>
        <%= f.number_field :experience %>
    </div>

    <div class="col-lg-4">
        <%= f.label :skills %>
        <%= f.text_field :skills %>
    </div>

    <div class="actions" style="margin-top:5px;">
        <%= f.submit "Update",:class => "btn btn-success" %>
    </div>

<%end%>