config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/error',to:'static_pages#error',as: :error
  get '/not_found',to:'static_pages#not_found',as: :not_found

  devise_for :users,controllers: { sessions: 'users/sessions' ,passwords: 'users/passwords',
                                    registrations:'users/registrations',confirmations:'users/confirmations'}

    get 'profile/student_dashboard' => 'profiles#student_dashboard', as: :student_dashboard
    get 'profile/employer_dashboard' => 'profiles#employer_dashboard', as: :employer_dashboard

    get 'profile/:id' => 'profiles#show' , as: :profile

  resources :tests do
    member do
     get :activate
     get :privacy
     get :result
    end
    resources :questions ,:only => [:new, :create]
  end

  resources :questions ,:only =>[:show]

  get 'taketest/:test_id' , to: 'enrollments#taketest' , as: :taketest

  get 'taketest/:test_id/finish',to: 'enrollments#finish',as: :finish
  get 'taketest/:test_id/timeup',to: 'enrollments#timeup'
  post 'taketest/:test_id/submit_clicked' ,to: 'enrollments#submit_clicked', as: :submit_clicked

  get 'show_current_question/:id', to: 'enrollments#show_current_question' ,as: :show_current_question

  post 'add_question_to_current_test/:test_id/:question_id' , to: 'tests#add_question_to_current_test' ,as: :add_question_to_current_test
  delete 'remove_question_from_current_test/:test_id/:question_id' , to: 'tests#remove_question_from_current_test' ,as: :remove_question_from_current_test

  get 'enroll_for_test/:test_id' , to: 'enrollments#enroll_for_test',as: :enroll_for_test

  get 'details/edit',to:'details#edit',as: :edit_details
  get '/details/edit_student_details',to:'details#edit_student_details',as: :edit_student_details
  get '/details/new_student_details',to:'details#new_student_details',as: :new_student_details
  post '/student_details',to:'details#create_student_details'
  put '/student_details',to:'details#update_student_details'
  patch '/student_details',to:'details#update_student_details'

  get '/details/edit_employer_details',to:'details#edit_employer_details',as: :edit_employer_details
  get '/details/new_employer_details',to:'details#new_employer_details',as: :new_employer_details
  post '/employer_details',to:'details#create_employer_details'
  put '/employer_details',to:'details#update_employer_details'
  patch '/employer_details',to:'details#update_employer_details'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :test

  serialize :response,Hash

  validates :test_id,
                    presence:true

  validates :student_id,
                      presence:true

  validates :score,
                  numericality:true

  validates :attempted, inclusion: { in: [ true, false ] }
  

  #instance method
  def record_start_time
    if self.start_time.nil?
      self.start_time=DateTime.now
      self.save
    end
  end

  def get_start_time
    self.start_time.getlocal
  end

  def save_response_for_question(response,question_id)
    unless (response.nil? || response.empty? || question_id.nil? || question_id.empty?)
      self.response[question_id]=response.is_a?(Array) ? response:[response]
      self.save
    end
  end

  def get_user_response
    self.response
  end

  def set_score(score)
    self.score=score
    set_attempted
    save
  end

  def set_attempted
    self.attempted=true
  end

  def submit_test
    @score=0
    #get user response
    user_response_hash=self.get_user_response
    #get correct response
    @test_questions=TestQuestion.get_test_questions_join(self.test_id)
    #calculate score
    @test_questions.each do |t|
      if user_response_hash["#{t.question.id}"]==t.question.correct_answer
        @score+=t.marks
      end
    end
    set_score(@score)
    #save score
    #lock_test
    return @score
  end

  #class methods
  def self.get_results_of_test(test)
    @result=Enrollment.where(test_id:test.id,attempted:true).order(score: :desc).joins(:student).pluck(:name,:username,:email,:score)
    return @result
  end

  def self.get_enrollment_for_test(test,current_user)
      #current enrollment
      Enrollment.find_by(test_id:test.id,student_id:current_user.id)
  end

  def self.enroll_user_for_test(test,current_user)
    Enrollment.create(test_id:test.id,student_id:current_user.id)
  end

  def self.tests_enrolled_by_user(current_user)
    #listss of tests enrolled by user
    Enrollment.where(student_id:current_user.id)
  end


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  include EnrollmentsHelper
  before_action :check_user
  before_action :check_student_profile,only:[:enroll_for_test,:taketest]
  before_action :get_test_by_id,only:[:enroll_for_test,:taketest,:show_current_question,:submit_clicked,:finish]
  before_action :get_enrollment,only:[:taketest,:submit_clicked,:finish]
  before_action :check_test_time,only:[:taketest,:submit_clicked]
#Method for test simulation which take test_id as paramater
#and start timer for test
#params[:test_id] test chosen by student
  def taketest
    #check_student_profile
    #get_test_by_id
    #get_enrollment(also check enrolled or not)
    #check_time
    join_data
    @enrollment.record_start_time
    @now=@enrollment.get_start_time
  end

  def show_current_question
    #get_test_by_id
    @current_question = Question.get_question_by_id(params[:id])
    respond_to do |format|
      format.js
    end
  end


  def submit_clicked
    #filter get_test_by_id
    #filter get_enrollment
    #filter time
    @question_id=params[:question][:id]
    @response=params[:response]
    @enrollment.save_response_for_question(@response,@question_id)
    join_data
    @now=@enrollment.get_start_time
    respond_to do |format|
      format.js
    end
  end

  def enroll_for_test
    #check_profile _complete
    @user=current_user
    @tests = Test.all.page(params[:page])
    Enrollment.enroll_user_for_test(@current_test,current_user)
    @enrolled_test= Enrollment.tests_enrolled_by_user(current_user).pluck(:test_id)
    respond_to do |format|
      format.js
    end
  end

  def finish
    #filter get_test_by_id
    #filter-get_enrollement
    @score=@enrollment.submit_test
    #for view
    @total_marks=@current_test.marks
    @total_noq=TestQuestion.get_test_questions_join(@current_test.id).size
    @attempted=@enrollment.response.count
    @percentage=(@score/@total_marks.to_f).round(4)*100
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def get_enrollment
    @enrollment=Enrollment.get_enrollment_for_test(@current_test,current_user)
    if @enrollment.nil?
      flash[:danger]="Enroll First"
      if request.xhr?
        render :js=> "window.location = #{student_dashboard_path.to_json}"
      else
        redirect_to student_dashboard_path
      end
    end
  end

  def get_test_by_id
    @current_test = Test.get_test_by_id(params[:test_id])
    if @current_test.nil?
      flash[:danger]="Test doesnt exist"
      if request.xhr?
        render :js=> "window.location = #{student_dashboard_path.to_json}"
      else
        redirect_to student_dashboard_path
      end
    end
  end

  def check_user
      unless current_user.type=="Student"
        flash[:danger]="Authorizaion Error"
        if request.xhr?
          render :js=> "window.location = #{error_path.to_json}"
        else
          redirect_to error_path
        end
      end
  end

  def check_student_profile
      if current_user.student_detail.nil?
          if request.xhr?
            flash[:danger]= 'Complete profile first'
            render :js => "window.location = #{new_student_details_path.to_json}"
          else
            flash[:danger]= 'Complete profile first'
            redirect_to new_student_details_path
          end
      end
  # end

  def check_test_time
    unless @enrollment.start_time.nil?
      #if user is trying to take test more than once
      if Time.now.utc > @enrollment.start_time.plus_with_duration(get_total_seconds(@current_test.duration))
        flash[:danger]="Time is over"
        #if not attempted and time is over ,call finish action
        unless @enrollment.attempted
          if request.xhr?
            render :js => "window.location = #{finish_path.to_json}"
          else
            redirect_to finish_path
          end
        else
          if request.xhr?
            render :js => "window.location = #{student_dashboard_path.to_json}"
          else
            redirect_to student_dashboard_path
          end
        end
      end
    end
  end

  def join_data
    #all questions in test
    @test_questions=TestQuestion.get_questions_of_test(@current_test)
    #filter attempted
    @unattempted=@test_questions.select{|t| question_attempted(t.question.id,@current_test.id)==false}
    #current_question is always first unqttempted
    unless @unattempted.empty?
      #select first question from unattempted list
      @current_question = @unattempted.first.question
      #get unattempted sorted by question ids
    else
      #if all are attempted then select first question from list
      #unqttempted will be empty
      @current_question=@test_questions.first.question
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper


  def getValue(test,question)
    en=Enrollment.find_by(test_id:test.id,student_id:current_user.id)
    en.response["#{question.id}"]
  end

  def check_marked(test,question,mark)
    en=Enrollment.find_by(test_id:test.id,student_id:current_user.id)
    en.response["#{question.id}"]==[mark]
  end

  def check_marked_2(test,question,mark)
    en=Enrollment.find_by(test_id:test.id,student_id:current_user.id)
    en.response["#{question.id}"].include?mark if en.response["#{question.id}"]!=nil
  end


  def get_question(id)
    return Question.find(id)
  end

  def question_attempted(q_id,test_id)
    en=Enrollment.find_by(test_id:test_id,student_id:current_user.id)
    en.response.key?("#{q_id}")
  end

  def get_total_seconds(t)
    total=t.hour*60*60 + t.min*60 + t.sec
    return total;
  end

end

app/views/enrollments/_current_selected_question.html.erb
<div class="">

  <strong>
    <%= current_question.question %>
  </strong>
  <!-- <%= params%> -->
  <%= form_tag(submit_clicked_path(@current_test),remote:true) %>
  <%= hidden_field(:question,:id,:value=>current_question[:id])%>
  <%= hidden_field(:test,:id,:value=>@current_test.id)%>
  <%- if current_question.question_type.to_i == 0 %>
          <%=number_field_tag "response",getValue(@current_test,current_question)%>

  <%- elsif current_question.question_type.to_i == 1 %>

      <%= radio_button_tag("response","A",check_marked(@current_test,current_question,"A"))%>
      <label for="">
        <%= current_question.options[0] %>
      </label>
      <br>

      <%= radio_button_tag("response","B",check_marked(@current_test,current_question,"B")) %>
      <label for="">
        <%= current_question.options[1] %>
      </label>
      <br>

      <%= radio_button_tag("response","C",check_marked(@current_test,current_question,"C")) %>
      <label for="">
        <%= current_question.options[2] %>
      </label>
      <br>

      <%= radio_button_tag("response","D",check_marked(@current_test,current_question,"D")) %>
      <label for="">
        <%= current_question.options[3] %>
      </label>
      <br>

  <% else %>
      <%=check_box_tag("response[]","A",check_marked_2(@current_test,current_question,"A"))%>
      <label for="">
        <%= current_question.options[0] %>
      </label>
      <br>

      <%=check_box_tag("response[]","B",check_marked_2(@current_test,current_question,"B"))%>
      <label for="">
        <%= current_question.options[1] %>
      </label>
      <br>

      <%=check_box_tag("response[]","C",check_marked_2(@current_test,current_question,"C"))%>
      <label for="">
        <%= current_question.options[2] %>
      </label>
      <br>

      <%=check_box_tag("response[]","D",check_marked_2(@current_test,current_question,"D"))%>
      <label for="">
        <%= current_question.options[3] %>
      </label>
      <%end%>

  <%= submit_tag("Submit",class:"btn btn-primary") %>

</div>

app/views/enrollments/enroll_for_test.js.erb
$('#yeild_div').html('<%= escape_javascript(render template: "profiles/student_dashboard" ) %>');

app/views/enrollments/finish.html.erb
<div>
  <h1>
    attempted <%=@attempted%> out of <%=@total_noq%>
  </h1>
</div>

<div>
  <h1>
    Score is <%=@score%> out of <%=@total_marks%>
  </h1>
</div>

<div>
  <h1>
    Percentage is <%=@percentage%> %
  </h1>
</div>

<div>
  <h1>

  </h1>
    <%=link_to "See Leaderboard",result_test_path(@current_test)%>
</div>

app/views/enrollments/finish.js.erb
$('#test').html('<%= escape_javascript(render template:"enrollments/finish.html.erb")%>');

app/views/enrollments/show_current_question.js.erb
$('#div_with_current_question').html('<%= escape_javascript(render "current_selected_question", current_question: @current_question) %>');

app/views/enrollments/submit_clicked.js.erb
$('#test').html('<%= escape_javascript(render template:"enrollments/taketest.html.erb")%>');

app/views/enrollments/taketest.html.erb
<div id="test">

<div class="panel panel-default">
    <div class="panel-heading">
        <h3><%= @current_test.name %></h3>
    </div>

    <div class="countdown panel-heading pull-right">
      <h3>Countdown</h3>
    </div>

    <div class="timer hidden">
          <h3><%=@current_test.duration.hour*60*60 + @current_test.duration.min*60 + @current_test.duration.sec%></h3>
          <h3><%=@now.hour*60*60 +@now.min*60 + @now.sec %></h3>
    </div>

    <div class="panel-body">
        <div class="col-lg-4 col-sm-4">
            <table class="table border-right">
                <thead>
                    <tr>
                        <th>Question</th>
                        <th>Marks</th>

                        <th>Attempted</th>
                    </tr>
                </thead>
                <tbody>
                    <% @test_questions.each do |test_question| %>
                    <tr>
                      <td>
                          <%if test_question.question==@current_question%>
                          <strong>
                            <%= link_to test_question.question.question,show_current_question_path(test_question.question,:test_id=>@current_test),remote: true%>
                          </strong>
                          <%elsif question_attempted(test_question.question.id,@current_test.id)%>
                          <strong>
                            <%= link_to test_question.question.question,show_current_question_path(test_question.question,:test_id=>@current_test),remote: true,style:"color:black;"%>
                          </strong>
                          <%else%>
                            <strong>
                              <%= link_to test_question.question.question,show_current_question_path(test_question.question,:test_id=>@current_test),remote: true,style:"color:green;" %>
                            </strong>
                        <%end%>
                        </td>

                        <td>
                          <%=  test_question.marks %>
                        </td>
                    </tr>

                    <%- end %>
                </tbody>

            </table>

        </div>

        <!-- Right -->
        <div class="col-lg-8">
            <div id="div_with_current_question">
                <%= render 'current_selected_question', current_question: @current_question %>
            </div>

        </div>

    </div>

      <!--footer  -->
    <div class="panel-footer">
      <%=link_to "Finish Test",finish_path(@current_test),class:"btn btn-success pull-right"%>
    </div>
</div>
</div>