config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/error',to:'static_pages#error',as: :error
  get '/not_found',to:'static_pages#not_found',as: :not_found

  devise_for :users,controllers: { sessions: 'users/sessions' ,passwords: 'users/passwords',
                                    registrations:'users/registrations',confirmations:'users/confirmations'}

    get 'profile/student_dashboard' => 'profiles#student_dashboard', as: :student_dashboard
    get 'profile/employer_dashboard' => 'profiles#employer_dashboard', as: :employer_dashboard

    get 'profile/:id' => 'profiles#show' , as: :profile

  resources :tests do
    member do
     get :activate
     get :privacy
     get :result
    end
    resources :questions ,:only => [:new, :create]
  end

  resources :questions ,:only =>[:show]

  get 'taketest/:test_id' , to: 'enrollments#taketest' , as: :taketest

  get 'taketest/:test_id/finish',to: 'enrollments#finish',as: :finish
  get 'taketest/:test_id/timeup',to: 'enrollments#timeup'
  post 'taketest/:test_id/submit_clicked' ,to: 'enrollments#submit_clicked', as: :submit_clicked

  get 'show_current_question/:id', to: 'enrollments#show_current_question' ,as: :show_current_question

  post 'add_question_to_current_test/:test_id/:question_id' , to: 'tests#add_question_to_current_test' ,as: :add_question_to_current_test
  delete 'remove_question_from_current_test/:test_id/:question_id' , to: 'tests#remove_question_from_current_test' ,as: :remove_question_from_current_test

  get 'enroll_for_test/:test_id' , to: 'enrollments#enroll_for_test',as: :enroll_for_test

  get 'details/edit',to:'details#edit',as: :edit_details
  get '/details/edit_student_details',to:'details#edit_student_details',as: :edit_student_details
  get '/details/new_student_details',to:'details#new_student_details',as: :new_student_details
  post '/student_details',to:'details#create_student_details'
  put '/student_details',to:'details#update_student_details'
  patch '/student_details',to:'details#update_student_details'

  get '/details/edit_employer_details',to:'details#edit_employer_details',as: :edit_employer_details
  get '/details/new_employer_details',to:'details#new_employer_details',as: :new_employer_details
  post '/employer_details',to:'details#create_employer_details'
  put '/employer_details',to:'details#update_employer_details'
  patch '/employer_details',to:'details#update_employer_details'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "TestLo" %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag "application", :media => "all" %>

        <!-- For third-generation iPad with high-resolution Retina display: -->
        <!-- Size should be 144 x 144 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

        <!-- For iPhone with high-resolution Retina display: -->
        <!-- Size should be 114 x 114 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

        <!-- For first- and second-generation iPad: -->
        <!-- Size should be 72 x 72 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <!-- Size should be 57 x 57 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

        <!-- For all other devices -->
        <!-- Size should be 32 x 32 pixels -->
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

        <%= javascript_include_tag "application" %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
    </head>
    <body>

        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://localhost:3000">TestLo</a>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav pull-right">
                        <%- if signed_in? %>
                        <li><%= link_to "Log Out", destroy_user_session_path  %></li>
                    <%- else %>
                        <li><%= link_to "Sign In", new_user_session_path  %></li>
                        <li><%= link_to "Sign Up", new_user_registration_path  %></li>
                        <%- end %>
                    </ul>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">

                <%- if signed_in? %>

                <%- if controller_name != "enrollments" %>
                <div class="col-lg-3">
                    <div class="well sidebar-nav">
                        <%= image_tag("profile_image.png") %>
                        <h3><%= current_user.name %></h3>
                        <ul class="nav nav-list">
                            <li>
                                <%= link_to "Edit Profile",edit_details_path,:class => "btn " %>
                            </li>
                            <%- if current_user.type == "Employer" %>
                            <li style="link-style-type:none;">
                                <%= link_to "My Tests", employer_dashboard_path,:class => "btn"%>
                                <%= link_to "Active Tests", employer_dashboard_path(:q=>"active"),:class => "btn"%>
                                <%= link_to "Inactive Tests", employer_dashboard_path(:q=>"inactive"),:class => "btn"%>
                                <%= link_to "Public Tests", employer_dashboard_path(:q=>"public"),:class => "btn"%>
                            </li>
                        <%- else %>
                            <li>
                                <%= link_to "All Active Tests",student_dashboard_path %>
                                <%= link_to "Enrolled",student_dashboard_path(:q=>"enrolled")%>
                                <%= link_to "Not Enrolled",student_dashboard_path(:q=>"not enrolled")%>
                                <%= link_to "Expired",student_dashboard_path(:q=>"expired")%>
                                <%= link_to "Attempted",student_dashboard_path(:q=>"attempted")%>
                            </li>
                            <%- end %>
                        </ul>
                    </div>
                    <!--/.well -->
                </div>
                <!--/span-->
                <%- end %>
                <%- end %>

                <%- if !signed_in? %>
                <div>
                <%- else %>
                    <%- if controller_name == "enrollments" %>
                    <div class="col-lg-12">
                    <%- else %>
                        <div class="col-lg-9">
                            <%- end %>
                            <%- end %>
                            <%= bootstrap_flash %>
                            <div id="yeild_div">
                                <%= yield %>
                            </div>

                        </div>
                    </div>
                    <!--/row-->

                </div>
                <!-- /container -->

            </body>
        </html>